name: Build and test
on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 8
      - uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: test
        shell: bash
        run: |
          set -o xtrace
          workdir="$HOME/go/src/yunion.io/x"
          mkdir -p "$workdir"
          mv "$HOME/work/kubecomps/kubecomps" "$workdir/"

          export GOPATH="$HOME/go"
          export GO111MODULE=off
          cd "$workdir/kubecomps"
          make test
